// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB2e2aq_wWhjv0fr_WDBX-qT5T-q2tVVnI',
    appId: '1:353464994828:web:9471d097686d848241b229',
    messagingSenderId: '353464994828',
    projectId: 'afg2026-2b7a1',
    authDomain: 'afg2026-2b7a1.firebaseapp.com',
    storageBucket: 'afg2026-2b7a1.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCIRJxRDmfiPnw7Y9OlRoQvoXQlxQIWGgg',
    appId: '1:353464994828:android:c54f13eaa472de9141b229',
    messagingSenderId: '353464994828',
    projectId: 'afg2026-2b7a1',
    storageBucket: 'afg2026-2b7a1.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA6c1A7Krgq-fK51otZwqpCPsocaVeRlRs',
    appId: '1:353464994828:ios:c0d65b71811b4dd641b229',
    messagingSenderId: '353464994828',
    projectId: 'afg2026-2b7a1',
    storageBucket: 'afg2026-2b7a1.firebasestorage.app',
    iosBundleId: 'com.example.smallBizManager',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA6c1A7Krgq-fK51otZwqpCPsocaVeRlRs',
    appId: '1:353464994828:ios:c0d65b71811b4dd641b229',
    messagingSenderId: '353464994828',
    projectId: 'afg2026-2b7a1',
    storageBucket: 'afg2026-2b7a1.firebasestorage.app',
    iosBundleId: 'com.example.smallBizManager',
  );
}
