// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAIi6A8t-QMRVxQ3OsbaoPeFAaVf5Ah1cw',
    appId: '1:1023409308484:web:6893488613679b158f4d11',
    messagingSenderId: '1023409308484',
    projectId: 'afg2026a',
    authDomain: 'afg2026a.firebaseapp.com',
    storageBucket: 'afg2026a.firebasestorage.app',
    measurementId: 'G-1XDE94QL0D',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBa3aUmjcGoywkRQ5rCaz_yaYcxDV08Fls',
    appId: '1:1023409308484:android:b0cffb0c41c110e58f4d11',
    messagingSenderId: '1023409308484',
    projectId: 'afg2026a',
    storageBucket: 'afg2026a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBTtTgX-0pU0JBwLdbC8sGONJV3-iW_bsA',
    appId: '1:1023409308484:ios:a30ec59912c72bad8f4d11',
    messagingSenderId: '1023409308484',
    projectId: 'afg2026a',
    storageBucket: 'afg2026a.firebasestorage.app',
    iosClientId: '1023409308484-ukssmasm50894vivf55sn1iej8hg5uo2.apps.googleusercontent.com',
    iosBundleId: 'com.example.smallBizManager',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBTtTgX-0pU0JBwLdbC8sGONJV3-iW_bsA',
    appId: '1:1023409308484:ios:a30ec59912c72bad8f4d11',
    messagingSenderId: '1023409308484',
    projectId: 'afg2026a',
    storageBucket: 'afg2026a.firebasestorage.app',
    iosClientId: '1023409308484-ukssmasm50894vivf55sn1iej8hg5uo2.apps.googleusercontent.com',
    iosBundleId: 'com.example.smallBizManager',
  );

}